### PR TITLE
Add shutdown callback to PluginManager

### PR DESCRIPTION
**Pull request by matwey**
Provide a way to use collectd plugin_register_shutdown API function.

### CODE REVIEW

**Comment by nickbabcock** [comment]
Hey thanks for the contribution!

Did you have something in mind that you were trying to create, but needed this API? In retrospect, I haven't seen a use for `PluginManager::initialize` either as both shutdown and initialize rely on global data (something that is not ergonomic in rust) and I'm considering whether this API should be removed in the future and force all initialization logic inside the `Plugin` (as plugins are dropped).

**Comment by matwey** [comment]
I need to run separate thread with event loop, that is common for all my `Plugin` instances. Similar to what is going on in `virt.c` plugin in collectd.

**Comment by nickbabcock** [comment]
Ah yes, great point -- shared resources across plugins. Ok, give me a bit to digest this.

Couple of other thoughts:

- You may not need to add the shutdown capability if the nop one is a fine default
- Since shutdown can fail, best to make it a `Result`

**Comment by matwey** [comment]
Probably shutdown capability may be merged with existing init capability?

**Pull request merged**
